@startuml
class Pizza{
 -Masa masa
 -Salsa salsa
 -Ingrediente ingrediente[]
}

class Pedido{
 -Pizza pizza
 -Calificacion calificacion
}

class Tienda{
 -Menu menu
 -Decoracion decoracion[]
 -Herramienta herramienta[1..]
 -Reputacion reputacion

 +agregarMejora : Accion(Mejora)
}

class Dia{
 -Pedido pedido[1..]
 -Dinero dinero
 -Historia historia[]

 +usarReputacion : Accion(Reputacion)
}

class Menu{
 -Receta receta[]
}

class Receta{
 -Ingrediente ingrediente[1..]
}

class Pizzero{

 +usarHorno : Accion(Horno)

 +usarCortador : Accion(Cortador)

 +usarCaja : Accion(Caja)

 +usarReceta : Accion(Receta[])

 +usarMejora : Accion(Mejora[])
}

class Cliente{

 +hacerPedido : Accion(Pedido)

 +calificarPedido : Accion(Calificacion)

 +darPropina : Accion(Propina)
}

class Competencia{

 +atraerCliente : Accion(Cliente[1..])
}

class Masa{}
class Salsa{}
class Ingrediente{}
class Calificacion{}
class Decoracion{}
class Herramienta{}
class Reputacion{}
class Dinero{}
class Historia{}
class Horno{}
class Cortador{}
class Caja{}
class Mejora{}
class Propina{}

@enduml